### ISSUE TITLE
Product-Type Data Setup

### ISSUE THREAD

**Issue by Valerie-Freeman** [Sheepish-Squirrels/bangazon-sprint-3#25]
## Task
1. Hard code json data for product-types in `seeders/product-types.json` Follow ERD for order (No faker data needed for this, just make up some product types)
2. Require json data into `build-db.js`

## Naming convention
- `seeders/product-types.json`
- `{
        "product-types": [
             {"name": "thing"},
             ...
        ]
     }`
- `let { product-types } = require("./seeders/product-types");`

**Comment by BrandonAllenGreen** [comment]
ticket finished
