### ISSUE TITLE
Product-Type Table Setup

### ISSUE THREAD

**Issue by Valerie-Freeman** [Sheepish-Squirrels/bangazon-sprint-3#26]
## Related ticked
#25 

## Task
1. Create model for product-types,  follow  ERD or faker data for attributes
`sequelize model:create --name Product-type --attributes [attributes go here]`
2. Write tableNames as `product-types`
3. Bulk Create product-types in `build-db.js`

## Dependencies
Product-type data

## Naming convention
- `models/Product-type.js`
- `tableName: "product-types"`
- `.then( () => {
  return models.Product-type.bulkCreate(product-types)
})`

**Comment by BrandonAllenGreen** [comment]
ticket finished
