### ISSUE TITLE
Payment-type Data Setup

### ISSUE THREAD

**Issue by Valerie-Freeman** [Sheepish-Squirrels/bangazon-sprint-3#29]
## Task
1. Build faker file for payment-types in generators folder (follow ERD for payment-type)
_I do not believe there is a faker method for visa, mastercard, etc._
2. Export generate function
3. Require generate function into `build-data.js`
4. Write json data to `seeders/payment-types.json`
5. Require json data into `build-db.js`

## Naming convention
- `generators/payment-type-faker.js`
- `module.exports.generatePaymentTypes`
- `return { payment-types }`
- `let payment-types = generatePaymentTypes();
let paymentTypeStream = createWriteStream('./seeders/payment-types.json');
paymentTypeStream.write(JSON.stringify(payment-types));`
- `let { payment-types } = require("./seeders/payment-types");`

**Comment by ajwolfcale** [comment]
Changing { payment-types } to { paymentTypes }.
