### ISSUE TITLE
Get Product Types

### ISSUE THREAD

**Issue by Valerie-Freeman** [Sheepish-Squirrels/bangazon-sprint-3#36]
## Related tickets
#2 #3 

### Write functionality to get all the product types from the product-type table. This is to be used for the customer posting a new product to sell. When they fill out the product detail form, they will get a list of product types to choose from. This will also be used for viewing a list of the product types on the homepage, if clicked.
- In `controllers/productCtrl.js` write a sequelize function to get all product types

## Naming convention
`controllers/productCtrl.js`
`module.exports.getProductTypes`

**Comment by BrandonAllenGreen** [comment]
reviewed and merged to master
