### ISSUE TITLE
Get Product By Id

### ISSUE THREAD

**Issue by Valerie-Freeman** [Sheepish-Squirrels/bangazon-sprint-3#44]
## Related tickets
#5 

### Write functionality to get one product from the database by the product id. This will be used for viewing the products details when the user clicks on a product hyperlink in any part of the application.
- In `controllers/productCtrl.js` write a sequelize function to get one product

## Dependencies
Product Id

## Naming convention
`controllers/productCtrl.js`
`module.exports.getProductById`

**Comment by BrandonAllenGreen** [comment]
reviewed and merged to master

**Comment by BrandonAllenGreen** [comment]
reviewed and merged to master
